### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by bacounts** [CodyHouse/cd-button-slide-effect-changelog#1]
The default demo is no longer working.

Also, is there a way to add a non-js version of this button? I like the slide effect and would love a more static version of it for certain projects that are less .js heavy.

**Comment by claudia-romano** [comment]
Hi there, what browser are using? I tested it on Chrome 88 and Firefox 86 and the demo is working fine. Thanks!

**Comment by bacounts** [comment]
This seems to be a Chrome 88 issue?! I tested It on Firefox and Safari, and it renders properly. See images, the black, unanimated button in Chrome and the blue animated button in Safari.

<img width="345" alt="Screen Shot 2021-02-26 at 7 08 58 AM" src="https://user-images.githubusercontent.com/6481954/109317798-f3789b00-7801-11eb-8386-0ff59b7e9611.png">
<img width="315" alt="Screen Shot 2021-02-26 at 7 09 19 AM" src="https://user-images.githubusercontent.com/6481954/109317797-f2e00480-7801-11eb-8b2f-35e1941d6193.png">

**Comment by bacounts** [comment]
This can now be marked as resolved. It was a browser cache issue.
